spring.application.name=coworking-space-management-system
server.port=8080

spring.datasource.url=${COWORKING_DB_URL:jdbc:mysql://localhost:3306/coworking_space?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${COWORKING_DB_USERNAME:root}
spring.datasource.password=${COWORKING_DB_PASSWORD:}
